# Generated by Django 5.2.7 on 2025-11-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
