# Generated by Django 5.2.7 on 2025-11-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
